AWS_REGION         = "us-west-2"
AVAILABILITY_ZONE  = "us-west-2b"
LAMBDA_RUNTIME     = "nodejs14.x"
LAMBDA_HANDLER     = "index.handler"
LAMBDA_DESCRIPTION = "Function to test network connectivity"
LAMBDA_NAME        = "ping-test"
LAMBDA_FILE        = "lambda_payload.zip"
LAMBDA_SOURCE_DIR  = "src/ping-test"